language:
  - swift
osx_image: xcode13.2.1
script:
  - xcodebuild -scheme SwiftExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=15.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
